### ISSUE TITLE
database can not created

### ISSUE THREAD

**Issue by skydiablo** [Overv/openstreetmap-tile-server#108]
i'm trying to deploy this image on my kubernetes cluster. this is my current "StatfulSet"

```YAML
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: osm-tile-server
  name: osm-tile-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: osm-tile-server
  serviceName: osm-tile-server
  template:
    metadata:
      labels:
        k8s-app: osm-tile-server
    spec:
      containers:
      - name: osm-tile-server
        image: overv/openstreetmap-tile-server:latest
        command: ["/run.sh"]
        args:
        - import
        env:
        - name: DL_PBF
          value: 'http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf'
        - name: DL_PBF_POLY
          value: 'http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern.poly'
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 2Gi
        volumeMounts:
        - mountPath: /var/lib/postgresql/12
          name: osm-tile-server
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: osm-tile-server
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 60Gi
      storageClassName: general
```

and here is the given pod log output:

```TXT
shared_buffers = 128MB
min_wal_size = 1GB
max_wal_size = 2GB
maintenance_work_mem = 256MB
# Suggested settings from
# https://github.com/openstreetmap/chef/blob/master/roles/tile.rb#L38-L45
max_connections = 250
temp_buffers = 32MB
work_mem = 128MB
wal_buffers = 1024kB
wal_writer_delay = 500ms
commit_delay = 10000
# checkpoint_segments = 60 # unrecognized in psql 10.7.1
max_wal_size = 2880MB
random_page_cost = 1.1
track_activity_query_size = 16384
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
listen_addresses = '*'
autovacuum = on
+ cat /etc/postgresql/12/main/conf.d/postgresql.custom.conf
+ service postgresql start
 * Starting PostgreSQL 12 database server
 * Error: /usr/lib/postgresql/12/bin/pg_ctl /usr/lib/postgresql/12/bin/pg_ctl start -D /var/lib/postgresql/12/main -l /var/log/postgresql/postgresql-12-main.log -s -o  -c config_file="/etc/postgresql/12/main/postgresql.conf"  exited with status 1: 
pg_ctl: directory "/var/lib/postgresql/12/main" is not a database cluster directory
   ...fail!
+ sudo -u postgres createuser renderer
createuser: error: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ sudo -u postgres createdb -E UTF8 -O renderer gis
createdb: error: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ sudo -u postgres psql -d gis -c 'CREATE EXTENSION postgis;'
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ sudo -u postgres psql -d gis -c 'CREATE EXTENSION hstore;'
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ sudo -u postgres psql -d gis -c 'ALTER TABLE geometry_columns OWNER TO renderer;'
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ sudo -u postgres psql -d gis -c 'ALTER TABLE spatial_ref_sys OWNER TO renderer;'
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ setPostgresPassword
+ sudo -u postgres psql -c 'ALTER USER renderer PASSWORD '\''renderer'\'''
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ '[' '!' -f /data.osm.pbf ']'
+ '[' -z http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf ']'
+ '[' -n http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf ']'
+ echo 'INFO: Download PBF file: http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf'
+ wget -nv http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf -O /data.osm.pbf
INFO: Download PBF file: http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf
2020-02-20 12:12:43 URL:http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf [94374362/94374362] -> "/data.osm.pbf" [1]
+ '[' -n http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern.poly ']'
+ echo 'INFO: Download PBF-POLY file: http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern.poly'
+ wget -nv http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern.poly -O /data.poly
INFO: Download PBF-POLY file: http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern.poly
2020-02-20 12:12:43 URL:http://download.geofabrik.de/europe/germany/mecklenburg-vorpommern.poly [2774/2774] -> "/data.poly" [1]
+ '[' disabled = enabled ']'
+ '[' -f /data.poly ']'
+ sudo -u renderer cp /data.poly /var/lib/mod_tile/data.poly
+ sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua --number-processes 4 -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /data.osm.pbf
osm2pgsql version 1.2.0 (64 bit id space)
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=11
Mid: pgsql, cache=800
Connection to database failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Connection to database failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
DB copy thread failed: Connecting to database.
+ sudo -u postgres psql -d gis -f indexes.sql
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ touch /var/lib/mod_tile/planet-import-complete
+ service postgresql stop
 * Stopping PostgreSQL 12 database server
   ...done.
+ exit 0
```

any idea to solve this problem?

> pg_ctl: directory "/var/lib/postgresql/12/main" is not a database cluster directory

greez & thx, volker...
