### ISSUE TITLE
Is it possible to get vector data and objects information in bounds?

### ISSUE THREAD

**Issue by Zemledelec** [Overv/openstreetmap-tile-server#123]

**Comment by Zemledelec** [comment]
I'd like to fetch points such as Countries, houses etc.  inside of some extent.

**Comment by Istador** [comment]
This project is using the old `Mapnik` software stack with `mod_tile`. The web server only serves rasterized images.

There is a new software stack developed by `Mapbox` using vectors. The software by the Mapbox company and the data formats are open source. Mapbox is a big financial contributor to OpenStreetMap (OSM) and is offering paid services. There is a big software community around it, for example custom styles that you can click together in the browser and customize on the fly.

The database files in the OSM PBF format released by OSM, and who everyone can download and use free of charge, which is used by this project, can't be used with the Mapbox software stack. The Mapbox company requires you to pay for their proprietary database files (and update files) to set up your own Mapbox server. Afaik there is no software to transform the free database files into their format (maybe with `ogr2ogr`?).

But, there are ways around it.

I'm no expert for this, but the last few hours I tried out [Tegola](https://github.com/go-spatial/tegola) (because of this issue, but I already had it on my todo list for the last years). It's a server software that can access the OSM postgresql database created by this project and output the data as `Mapbox Vector Tiles` for other applications to use (e.g. by `leaflet`). It requires some work to set up and configure but it basically works (e.g. you have to write your own SQL queries and define what data to extract).

---

The following example shows Tegola serving buildings for Hamburg.

![tegola](https://user-images.githubusercontent.com/8825444/78872743-0481b780-7a4a-11ea-9aa6-714fc425c2b2.png)

**docker-compose.yml**:
```yml
version: "3.7"

volumes:
  osm-data:
  osm-tile:
  osm-nodes:

services:
  tiles:
    build: ./openstreetmap-tile-server/
    #image: overv/openstreetmap-tile-server:1.3.11
    command: run
    environment:
    - THREADS=8
    - DOWNLOAD_PBF=https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf
    - DOWNLOAD_POLY=https://download.geofabrik.de/europe/germany/hamburg.poly
    - OSM2PGSQL_EXRA_ARGS="-C 4096 --flat-nodes /nodes/flat_nodes.bin"
    volumes:
    - osm-data:/var/lib/postgresql/12/main
    - osm-tile:/var/lib/mod_tile
    - osm-nodes:/nodes
    shm_size: 512M
    ports:
    - 0.0.0.0:80:80

  tegola:
    image: gospatial/tegola:v0.10.4
    command: serve --config=/opt/tegola_config/config.toml
    volumes:
    - ./tegola.toml:/opt/tegola_config/config.toml
    ports:
    - 0.0.0.0:8080:8080
```

**tegola.toml**:
```toml
[webserver]
port = ":8080"

    [webserver.headers]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate"

[cache]
type     = "file"
basepath = "/tmp/tegola"

[[providers]]
name            = "osm_postgis"
type            = "postgis"
host            = "tiles"
port            = 5432
database        = "gis"
user            = "renderer"
password        = "renderer"
srid            = 3857
max_connections = 50

    [[providers.layers]]
    name               = "buildings"
    geometry_fieldname = "way"
    id_fieldname       = "osm_id"
    sql = "SELECT osm_id, name, tags, ST_AsBinary(way) as way FROM planet_osm_polygon WHERE building IS NOT NULL AND building != 'no' AND way && !BBOX!"

[[maps]]
name = "ajt"

    [[maps.layers]]
    name           = "buildings"
    provider_layer = "osm_postgis.buildings"
    dont_simplify  = true
    dont_clip      = true
    min_zoom       = 14
    max_zoom       = 18
```

**commands**:
```bash
# clone and build this project, because the newest version isn't on docker hub yet
git  clone  https://github.com/Overv/openstreetmap-tile-server
docker-compose  build

# import postgresql database
docker-compose  run  tiles  import

# start webserver that serves rendered raster images
docker-compose  up  -d  tiles

# pre-render tiles
docker-compose  exec  tiles  render_list  -a  -f  -m ajt  -z 0  -Z 8
# GET http://localhost/

# start vector server
docker-compose  up  -d  tegola
# GET http://localhost:8080/#14.22/53.55046/9.98505
```
