### ISSUE TITLE
ERROR:  role "renderer" does not exist

### ISSUE THREAD

**Issue by maheshrpm** [Overv/openstreetmap-tile-server#131]
I tried many times by completely wiping the container, volume and image. But still no success. Log says role "renderer" not found.

![image](https://user-images.githubusercontent.com/195490/80940870-811e7080-8e13-11ea-8135-072607810e0b.png)

And at the end

![image](https://user-images.githubusercontent.com/195490/80940937-aa3f0100-8e13-11ea-96ea-e60aacb4b163.png)

**Comment by VShkaberda** [comment]
The error `ERROR:  role "renderer" does not exist` was mentioned earlier in https://github.com/Overv/openstreetmap-tile-server/issues/128#issuecomment-620077102. I had the same issue once after I installed `postgresql`, `postgresql-contrib` and `postgresql-client` on main system (Ubuntu 18.04) and made some manipulations using them, but I didn't try to reproduce it.

**Comment by maheshrpm** [comment]
> The error `ERROR: role "renderer" does not exist` was mentioned earlier in [#128 (comment)](https://github.com/Overv/openstreetmap-tile-server/issues/128#issuecomment-620077102). I had the same issue once after I installed `postgresql`, `postgresql-contrib` and `postgresql-client` on main system (Ubuntu 18.04) and made some manipulations using them, but I didn't try to reproduce it.

I read your [comments](https://github.com/Overv/openstreetmap-tile-server/issues/128#issuecomment-620664161) and tried with new pbf file and volume. But nothing happens.

**Comment by Surfoo** [comment]
I have the same issue, here my docker-compose.yaml :

```
version: "3"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:
    external: true

services:
  osm-server:
    container_name: osm_server
    image: overv/openstreetmap-tile-server:latest
    ports:
      - 8080:80
      - 5432:5432
    volumes:
      - /media/nobackup/osm/france.osm.pbf:/data.osm.pbf
      - /media/nobackup/osm/france.poly:/data.poly
      - openstreetmap-data:/var/lib/postgresql/12/main
      - openstreetmap-rendered-tiles:/var/lib/mod_tile
    environment:
      - ALLOW_CORS=enabled
    command: run

```
