### ISSUE TITLE
command: import run one by one

### ISSUE THREAD

**Issue by isologub29** [Overv/openstreetmap-tile-server#136]
Is it possible to run import and run commands one by one?

My configs look like this

```
  services:
    osm-tile-backend:
      image: overv/openstreetmap-tile-server:latest
      container_name: osm-tile-backend-container
      environment:
        DOWNLOAD_PBF: http://download.geofabrik.de/europe/belarus-latest.osm.pbf
        DOWNLOAD_POLY: http://download.geofabrik.de/europe/belarus.poly
      command: bash -c "import && run"
      ports:
        - "5001:80"
      volumes:
        - "openstreetmap-data:/var/lib/postgresql/12/main"

```

```
volumes:
  openstreetmap-data:
    external: true
```

However, I get this error
```
usage: <import|run>
commands:
    import: Set up the database and import /data.osm.pbf
    run: Runs Apache and renderd to serve tiles at /tile/{z}/{x}/{y}.png
environment variables:
    THREADS: defines number of threads used for importing / tile rendering
    UPDATES: consecutive updates (enabled/disabled)
+ '[' 3 -ne 1 ']'
+ echo 'usage: <import|run>'
+ echo commands:
+ echo '    import: Set up the database and import /data.osm.pbf'
+ echo '    run: Runs Apache and renderd to serve tiles at /tile/{z}/{x}/{y}.png'
+ echo 'environment variables:'
+ echo '    THREADS: defines number of threads used for importing / tile rendering'
+ echo '    UPDATES: consecutive updates (enabled/disabled)'
+ exit 1
```
