### ISSUE TITLE
Connect to remote database

### ISSUE THREAD

**Issue by alfredott** [Overv/openstreetmap-tile-server#144]
Hello,

First, thank you very much for your work.

I would like to know if it would be possible to use all of your docker image, except the postgresql database that is inside of it.
In place, a remote postgresql database would be used, so as to be able to manage the database and the rest of the work separately. 

For example, it would enable us to add redundancy the postgresql database, for high availability concerns, or to fill up another database, to make a data update, and then switch the database used by the image. (This is one of my use cases, since I want to update my data every month or so, in an offline network)

If you think so, a pull request could be made. I've tried to check what parts of the files would have to change, and I think I could work on it.

Sorry if I missed another issue asking the same thing.
What is your opinion regarding this feature ? Is anyone also interested in it ?

Thanks again for your work, and thanks in advance for your answer.

**Comment by alfredott** [comment]
Hello,

FYI, I am currently working on this feature.
I used the [postgis/postgis](https://registry.hub.docker.com/r/postgis/postgis/) docker image to create the database, and I modified this project's `Dockerfile` and `run.sh` to use that database instead of the local one, during the `import` and `run` phases.

It quite works, but my main concern is how to make it configurable, since the database work is shared between the `Dockerfile` (pre-`docker run`) and the `run.sh` (post-`docker run`).
Thus, it's easy to disable the postgre database completely, but harder to disable it on demand. (without breaking the way it currently works)
Also, I started to think that besides taking the database out of the image, it would also be a good idea to separate the `import` phase (osm2pgsql) from the `run` phase (mapnik, renderd, apache, ...)

Finally, the more I play with it, the more I'm starting to think that a Docker Compose would be the best idea to split this image's components.

Any opinion appreciated :)

**Comment by Istador** [comment]
Give the database host, port, user, password and name as optional env variables to the docker container.
If they are given, the `import` and `run` don't start a database sevice, but use the one given.

Then it could be used with compose like so:
```yml
version: "3.7"

volumes:
  openstreetmap-data:
  openstreetmap-rendered-tiles:

services:
  osmdb:
     image: postgis/postgis:12.3
    volumes:
    - openstreetmap-data:/var/lib/postgresql/12/main
    shm_size: 128M
    restart: always
    # [...]
  osm:
    image: overv/openstreetmap-tile-server:1.4.0
    command: run
    environment:
    - THREADS=4
    - OSM_DB_HOST=osmdb
    - OSM_DB_PORT=5432
    - OSM_DB_USER=postgres
    - OSM_DB_PASS=secret
    - OSM_DB_NAME=gis
    volumes:
    - openstreetmap-rendered-tiles:/var/lib/mod_tile
    ports:
    - 0.0.0.0:80:80
    restart: always
```

I don't think separating `import` and `run` too much is a good idea. Both are dependent on each other, like running with the same/similar environment variables. The `run` phase also calls `osm2pgsql` when updates are enabled.

The only "database work" in the Dockerfile is installing it and copying the config file. That can be neglected, and is the responsibility of the externally linked database instance (`osmdb` in this example). Changing it doesn't seem to be necessary at all to me. Because if you don't use an external database, the software for it needs to be there, so that the image works out of the box. As easy as possible without setting up an extra database service.

An alternative approach for the Dockerfile could be to have it multi-staged with different targets, and then offer different tags via docker hub. For example a image doesn't contain protgresql at all (to reduce its size), e.g. `1.4.0-nodb`.
