### ISSUE TITLE
Frontend to the database

### ISSUE THREAD

**Issue by MacaScull** [Overv/openstreetmap-tile-server#166]
Is there a possible way to view the database and its contents, either in a frontend connection or something else that is easy to read?

**Comment by Istador** [comment]
The `openstreetmap-tile-server` runs a `postgresql` database, which can be accessed on port `5432`. It's accessible when you are inside of the container (e.g. with `sudo -u postgres psql`) or from other containers in the same docker network. The port is not exposed to the outside - you could change this to access it easily from the host, but I'd advise against it for security reasons.

Two common web based admins:
- `phppgadmin` (UI similar to `phpmyadmin`)
- `pgAdmin 4`

Both have docker images that can be connected to the database of the `openstreetmap-tile-server`, by adding them to the same docker network (e.g. by defining them in the same `docker-compose.yml` file, or by providing additional network argument(s) when running `docker run` manually).

For `phppgadmin` you need to add the hostname of the database via an environment variable (e.g. `DATABASE_HOST` or `PHP_PG_ADMIN_SERVER_HOST`) (with `docker-compose`, the hostname is the name of the service - I'd advise against IPs as they might change dynamically on restarts).

`pgAdmin 4` gets the server config at runtime over the web interface.

**Comment by MacaScull** [comment]
How would this look in a docker-compose file as Ive added it into the docker-compose but when I log into pgadmin there are no servers there. My current docker-compose file looks like this:

```
version: "3.7"

volumes:
  osm-data:
  osm-tile:
  osm-nodes:

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
    - tiles
    ports:
    - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: macascull@email.com
      PGADMIN_DEFAULT_PASSWORD: fakepassword
  tiles:
    # build: ./openstreetmap-tile-server/
    image: overv/openstreetmap-tile-server
    command: run
    environment:
    - THREADS=8
    - DOWNLOAD_PBF=https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf
    - ALLOW_CORS=enabled
    volumes:
    - osm-data:/var/lib/postgresql/12/main
    - osm-tile:/var/lib/mod_tile
    - osm-nodes:/nodes
    shm_size: 512M
    ports:
    - 8000:80

  tegola:
    image: gospatial/tegola
    command: serve --config=/opt/tegola_config/config.toml
    volumes:
    - ./tegola.toml:/opt/tegola_config/config.toml
    ports:
    - 8080:8080
```

I think im missing a connection somewhere or I have to expose the DB and then run pgadmin.
