### ISSUE TITLE
My docker-compose won't render tiles

### ISSUE THREAD

**Issue by stefanodecillis** [Overv/openstreetmap-tile-server#175]
Hello,

sorry to bother but I'm facing some issue regarding the docker image. In particular, I make the import of my .pbf and the run without problems (I guess), the demo-leaflet.html runs but it doesn't render any tile. Also it fails in making single tile requests. 
My `docker-compose.yml` looks like:

```
[...]
osm-tile-service:
    container_name: osm-tile-service
    image: overv/openstreetmap-tile-server
    volumes:
      - ./osm-tile/render/data:/var/lib/postgresql/12/main
      - ./data/rideout-latest.osm.pbf:/data.osm.pbf
      - ./osm-tile/rideout-latest.poly:/data.poly
      - ./osm-tile/render/tile:/var/lib/mod_tile
    ports: 
      - 852:80
    environment: 
      - UPDATES=enabled
      - ALLOW_CORS=enabled
    command: "import"

```

In the README.md uses a volume - I tried also the volume but it doesn't work. 
I think this is only an error that it occurs to me but it looks everything fine. Can you help me with it?

I'm leaving here some logs:

```

Mapnik LOG> 2021-03-26 22:26:28: warning: unable to find face-name 'Noto Sans Syriac Eastern Regular' in FontSet 'fontset-2'

Mapnik LOG> 2021-03-26 22:26:28: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-2'

Mapnik LOG> 2021-03-26 22:26:28: warning: unable to find face-name 'HanaMinA Regular' in FontSet 'fontset-2'

Mapnik LOG> 2021-03-26 22:26:28: warning: unable to find face-name 'HanaMinB Regular' in FontSet 'fontset-2'

Mapnik LOG> 2021-03-26 22:26:28: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'

renderd[150]: Using web mercator projection settings

renderd[150]: Using web mercator projection settings

renderd[150]: Using web mercator projection settings

renderd[150]: Using web mercator projection settings

renderd[150]: DEBUG: Got incoming connection, fd 4, number 1

renderd[150]: DEBUG: Got incoming request with protocol version 2

renderd[150]: DEBUG: Got command RenderPrio fd(4) xml(ajt), z(8), x(129), y(93), mime(image/png), options()

renderd[150]: DEBUG: START TILE ajt 8 128-135 88-95, new metatile

renderd[150]: Rendering projected coordinates 8 128 88 -> 0.000000|5009377.085700 1252344.271425|6261721.357125 to a 8 x 8 tile

renderd[150]: DEBUG: DONE TILE ajt 8 128-135 88-95 in 0.970 seconds

[...]


renderd[150]: DEBUG: Sending render cmd(3 ajt 8/135/93) with protocol version 2 to fd 4

renderd[150]: DEBUG: Sending render cmd(3 ajt 8/135/94) with protocol version 2 to fd 11

renderd[150]: DEBUG: Sending render cmd(3 ajt 8/135/92) with protocol version 2 to fd 9

renderd[150]: DEBUG: Connection 0, fd 4 closed, now 4 left

renderd[150]: DEBUG: Connection 3, fd 11 closed, now 3 left

renderd[150]: DEBUG: Connection 1, fd 9 closed, now 2 left

renderd[150]: DEBUG: DONE TILE ajt 8 136-143 88-95 in 0.961 seconds

debug: Creating and writing a metatile to /var/lib/mod_tile/ajt/8/0/0/0/133/136.meta


renderd[150]: DEBUG: Sending render cmd(3 ajt 8/136/93) with protocol version 2 to fd 8

renderd[150]: DEBUG: Sending render cmd(3 ajt 8/136/92) with protocol version 2 to fd 10

renderd[150]: DEBUG: Connection 0, fd 8 closed, now 1 left

renderd[150]: DEBUG: Connection 0, fd 10 closed, now 0 left
```
