### ISSUE TITLE
Can you send compose file?

### ISSUE THREAD

**Issue by roysbike** [Overv/openstreetmap-tile-server#18]
Please , send me docker-compose.yml

**Comment by Overv** [comment]
What?

**Comment by Istador** [comment]
A very rudimentary `docker-compose.yml` with just the basics to get the idea:

```yml
version: "3.7"

volumes:
  openstreetmap-data:
  openstreetmap-rendered-tiles:

services:
  osm:
    image: overv/openstreetmap-tile-server
    command: run
    environment:
    - THREADS=4
    volumes:
    - openstreetmap-data:/var/lib/postgresql/10/main
    - openstreetmap-rendered-tiles:/var/lib/mod_tile
    ports:
    - 0.0.0.0:80:80
    shm_size: 128M
    restart: always
```

Before the service can be started and used, the database needs to be initialized:
```bash
# download PBF file
wget  -O data.osm.pbf  https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf

# initializes the database and import the PBF file
docker-compose  run  -v "/`pwd`/data.osm.pbf":/data.osm.pbf  osm  import

# start the service
docker-compose  up  -d

# pre render all tiles on zoom levels 0 to 5
docker-compose  exec  osm  render_list  -a  -f  -m ajt  -z 0  -Z 5
```
