### ISSUE TITLE
Rapid in and out zoom crashes container

### ISSUE THREAD

**Issue by hyprstack** [Overv/openstreetmap-tile-server#189]
I am getting the following logs after I zoom in and out rapidly on multiple regions of the map without letting it render.

EDIT NOTE: I am running docker on a mac

```
map_1  | renderd[146]: DEBUG: Got command RenderPrio fd(34) xml(ajt), z(13), x(6610), y(4063), mime(image/png), options()
map_1  | renderd[146]: DEBUG: Got incoming connection, fd 35, number 24
map_1  | renderd[146]: DEBUG: Got incoming request with protocol version 2
map_1  | renderd[146]: DEBUG: Got command RenderPrio fd(35) xml(ajt), z(13), x(6610), y(4064), mime(image/png), options()
map_1  | renderd[146]: DEBUG: START TILE ajt 13 6608-6615 4064-4071, new metatile
map_1  | renderd[146]: Rendering projected coordinates 13 6608 4064 -> 12288628.163358|117407.275446 12327763.921840|156543.033928 to a 8 x 8 tile
map_1  | renderd[146]: DEBUG: Got incoming connection, fd 36, number 25
map_1  | renderd[146]: DEBUG: Got incoming request with protocol version 2
map_1  | renderd[146]: DEBUG: Got command RenderPrio fd(36) xml(ajt), z(13), x(6610), y(4062), mime(image/png), options()
map_1  | renderd[146]: DEBUG: Got incoming connection, fd 37, number 26
map_1  | renderd[146]: DEBUG: Got incoming request with protocol version 2
map_1  | renderd[146]: DEBUG: Got command RenderLow fd(37) xml(ajt), z(13), x(6459), y(4054), mime(image/png), options()
map_1  | renderd[146]: DEBUG: Connection 25, fd 37 closed, now 25 left
map_1  | /run.sh: line 123:   145 Killed                  sudo -u renderer renderd -f -c /usr/local/etc/renderd.conf
map_1  | + service postgresql stop
map_1  |  * Stopping PostgreSQL 12 database server
map_1  |    ...done.
map_1  | + exit 0
map_1 exited with code 0
```

I have written the following bash script and compose file to run everything under one command:

```
#!/bin/sh

dockerDown=`docker info | grep -qi "ERROR" && echo "stopped"`

if [ $dockerDown ]
then
  echo "\n ********* Please start docker before running this script ********* \n"
  exit 1
fi

skipInstall="no"
read -p "Have you imported the maps already and just want to run the app (y/n)?" choice
case "$choice" in
  y|Y ) skipInstall="yes";;
  n|N ) skipInstall="no";;
  * ) skipInstall="no";;
esac

pbfUrl='https://download.geofabrik.de/asia/malaysia-singapore-brunei-latest.osm.pbf'
#polyUrl='https://download.geofabrik.de/asia/malaysia-singapore-brunei.poly'
#-e DOWNLOAD_POLY=$polyUrl \

docker volume create openstreetmap-data
docker volume create openstreetmap-rendered-tiles

if [ $skipInstall = "no" ]
then
  echo "\n ***** IF THIS IS THE FIRST TIME, YOU MIGHT WANT TO GO GET A CUP OF COFFEE WHILE YOU WAIT ***** \n"
  docker run \
      -e DOWNLOAD_PBF=$pbfUrl \
      -v openstreetmap-data:/var/lib/postgresql/12/main \
      -v openstreetmap-rendered-tiles:/var/lib/mod_tile \
      overv/openstreetmap-tile-server \
      import

  echo "Finished Postgres container!"
fi

echo "\n *** BOOTING UP SERVER CONTAINER *** \n"

docker compose up
```

and 

```
version: '3'

services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
      - openstreetmap-rendered-tiles:/var/lib/mod_tile
    environment:
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS="-C 4096"
      - AUTOVACUUM=off
      - OSM2PGSQL_EXTRA_ARGS="--flat-nodes /nodes/flat_nodes.bin"
    ports:
      - "8080:80"
    command: "run"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:
    external: true
```

I initially thought it could be that my app, which uses openlayers to render the map might be causing the issue, but then visited the demo app at localhost:8080 and had the same result. 

Any idea what might be causing this?
