### ISSUE TITLE
Error after update tiles

### ISSUE THREAD

**Issue by mvbelik** [Overv/openstreetmap-tile-server#253]
Hi, I have such a problem, after updating the data to the tile server, there was such an error:
```
renderd[150]: DEBUG: Connection 6, fd 30 closed, now 6 left
renderd[150]: DEBUG: Got incoming connection, fd 30, number 7
renderd[150]: DEBUG: Got incoming request with protocol version 2
renderd[150]: DEBUG: Got command Dirty fd(30) xml(ajt), z(18), x(180355), y(91335), mime(image/png), options()
renderd[150]: DEBUG: Sending NotDone response(4)
renderd[150]: DEBUG: Sending render cmd(4 ajt 18/180355/91335) with protocol version 2 to fd 30
renderd[150]: WARNING: Failed to send render cmd on fd 30
send error: Broken pipe
```

Auto-update also does not work, although there is an auto-update flag in the docker.

**Comment by mvbelik** [comment]
I using docker compose:
```
version: '3'
services:
  tiles_start:
    image: overv/openstreetmap-tile-server:v1.8.2
    restart: always
    shm_size: 128G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 5s
      timeout: 10s
      retries: 3
    container_name: tiles-server
    volumes:
      - "{{tiles_db_dir}}:/var/lib/postgresql/12/main"
      - "{{tiles_cache_dir}}:/var/lib/mod_tile"
      - "{{ settings_dir }}/postgresql_tiles.conf:/etc/postgresql/12/main/postgresql.conf"
      - "{{ settings_dir }}/postgresql.custom.conf:/etc/postgresql/12/main/conf.d/postgresql.custom.conf"
    ports:
      - "8082:80"
      - "5433:5432"
    environment:
      THREADS: "{{tiles_work_threads}}"
      PGPASSWORD: "{{tiles_db_pass}}"
      OSM2PGSQL_EXTRA_ARGS: "-C 32768"
      OSM2PGSQL_EXTRA_ARGS: "--flat-nodes /nodes/flat_nodes.bin"
      UPDATES: "enabled" 
    command: "run"
```

**Comment by mvbelik** [comment]
For import i using another docker compose file:
```
version: '3'
services:
  tiles_import:
    image: overv/openstreetmap-tile-server:v1.8.2
    container_name: tiles-import
    volumes:
      - "{{tiles_pbf_dir}}/planet-latest.osm.pbf:/data.osm.pbf"
      - "{{tiles_db_dir}}:/var/lib/postgresql/12/main"
     environment:
      THREADS: "{{tiles_import_threads}}"
      OSM2PGSQL_EXTRA_ARGS: "--flat-nodes /nodes/flat_nodes.bin"
      UPDATES: enabled
    command: "import"                                                                                                                                                              
```
