### ISSUE TITLE
tuning & monitoring

### ISSUE THREAD

**Issue by hugokoopmans** [Overv/openstreetmap-tile-server#32]
hi there, I have set up a tileserver for our wildlife protection organisation Sensing Clues (see [here](https://sensingclues.org/) ).
I have set up a docker host on a 4 core 16 GB RAM server.
The tileserver is setup and I imported 7 countries ( NL, Tanzanie, Kenia, South Africa, Namibia, Zambia, Zimbabwe) I expect to load more countries soon.

My question/issue is how do monitor what is going on on the tile server?

I have pre-renderd tiles  like so:

    render_list -n 8 -a  -f  -m ajt  -z 9  -Z 15

And tested with some zoom levels from 0 to x but if I look at the volumes in docker with

    docker system df -v

I see 57 GB of postgresql data but only see 350 MB of renderd tiles?

VOLUME NAME                                                        LINKS               SIZE
9bb722d5661210d1cc218bfa29f951453f01b6344f2999fdd92661bb890bb919   1                   424B
openstreetmap-data                                                 1                   57.25GB
openstreetmap-rendered-tiles                                       1                   334.9MB

No matter what I do with render_list seems it does not pre-render any more tiles? 

Memory usage:

```
CONTAINER ID        NAME                                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
acb8612ddd66        tileserver                          395.06%             3.697GiB / 15.66GiB   23.60%              10.9MB / 128MB      30GB / 262MB        235
69f87448cb4a        registry                            0.00%               4.355MiB / 15.66GiB   0.03%               9.73MB / 99.2MB     2.15GB / 0B         13
872f5d1e6647        portainer                           0.00%               8.332MiB / 15.66GiB   0.05%               9.91MB / 59.3MB     7.73GB / 93.3MB     14
9a5bc06c2d41        hello                               0.00%               2.086MiB / 15.66GiB   0.01%               31.9kB / 0B         4.33MB / 0B         2
84ffec2790ff        letsencrypt-nginx-proxy-companion   0.12%               11.08MiB / 15.66GiB   0.07%               130kB / 70.5kB      3.68GB / 73.7kB     18
f37924d45aa6        nginx-proxy                         0.12%               14.43MiB / 15.66GiB   0.09%               335MB / 350MB       3.69GB / 377kB      33

```

If i look at htop postgresql seems busy, also with some jobs over more then 3 hours ????

     renderer gis [local] select

I in a previous post i played around with THREADS and shm_size the docker-compose yml

Assumptions / Questions:

1. As I have only 4 cores THREADS > 8 seems not usefull? I do not see any impact
2. As I have 16 GB of RAM and this is a more or less dedicated tileserver I hardly see the memory usages exceed 25% . How can I make use of more memory? 
3. I am on postgres 10 is the latest image on 11 available? I have seen moderate speed increas but especially on the import part, does it also speed up rendering itself?
4. Are there any ways to monitor and understand better if and how the renderd process actually has renderd tiles? How many tiles are actually prerenderd etc etc. With 335 MB in the renderd_tiles folder something seems not right?
5. I have seen posts that pre_rendering takes a lot of time, but that is in hours not in days my tileserver is now up for quite a while (week) I have uses render_list from within docker via exec but again I do not know when it is finished what result to expect and how to optimize pre-rendering.

For completeness my current docker-compose file:

```
version: '3'
services:
  tileserver:
    container_name: tileserver
    image: overv/openstreetmap-tile-server
    restart: always
    ports:
        - "8099:80"
    volumes:
        - 'openstreetmap-data:/var/lib/postgresql/10/main'
        - 'openstreetmap-rendered-tiles:/var/lib/mod_tile'
        - '/data/docker/tileserver:/data'
    environment:
        THREADS: 8
    shm_size: 256M
    command: run

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:
    external: true

```

**Comment by Istador** [comment]
> 4. Are there any ways to monitor and understand better if and how the renderd process actually has renderd tiles? How many tiles are actually prerenderd etc etc. With 335 MB in the renderd_tiles folder something seems not right?

I use (among other tools) [munin](https://en.wikipedia.org/wiki/Munin_(software)) to monitor a few servers. Luckily `mod_tile` does come with [munin plugin scripts](https://github.com/SomeoneElseOSM/mod_tile/tree/master/munin) to monitor the rendering process. So they should already be present inside your container, you might just need to `exec`ute them properly.

`apache2` and `postgresql`, that run inside the container, can also be monitored by munin, but for those two there are also other tool(s) around to monitor them.

---

To inspect what currently is being worked on, there is a log of renderd that can be watched via docker:
```
$ docker-compose logs --follow tileserver
```

BTW: docker does save but not rotate these logs by default, so it (slowly) grows and grows and grows over time until the harddisk (of `/var/lib/docker`) is full. It might make sense to configure a log rotation for it, e.g. like this:
```yml
services:
  tileserver:
    # ...
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-files: "10"
```

As for the `apache2` and `postresql` services running inside of the container: they are started with `service` so their runtime logs should by accessible via `journalctl`, but both should also have logfiles inside `/var/log/` by default.
