### ISSUE TITLE
Shared memeory size parameter with Synology Docker variant

### ISSUE THREAD

**Issue by gsontheimer** [Overv/openstreetmap-tile-server#387]
When running Docker containers of openstreetmap-tile-server on my PC I can use the --shm-size parameter to increase the shared memory size.

The Synology implementation of Docker does not allow to pass parameters at run time (at least I have found no way).

Is there a way to use environment varaibles to achieve the same purpose? could the code be changed so that environment variables could set the size of the shared memory?

Gerhard

**Comment by Istador** [comment]
No, this is not possible via environment variables, because this is a setting outside of the control of the docker container.

This seems to be a workaround: https://github.com/jlesage/docker-firefox/issues/16#issuecomment-744742817

Besides that if you can't control it, you could change the postgres configuration to lower the default setting for shared memory of `128M` to below `64M` (docker default).

**Comment by harald79** [comment]
Since the release of DSM 7.2, Docker has introduced new features. Within the Container Manager, users can now input a YAML configuration for Docker Compose under the "Projects" section. This configuration is used to build the container. Attached is an example where the SHM (shared memory) is configured to 512MB.

```
version: '3.7'

services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - /volume2/docker/osm/database:/data/database/
      - /volume2/docker/osm/tiles:/data/tiles/
    ports:
      - "8123:80"
    command: "run"
    shm_size: 512m
```
