### ISSUE TITLE
Only renders Luxemburg

### ISSUE THREAD

**Issue by Eric-Arz** [Overv/openstreetmap-tile-server#392]
Trying to get this working with a custom region and docker compose

```
---
services:
  tileserver:
    image: overv/openstreetmap-tile-server:latest
    command: run
    restart: always
    ports:
      - 8080:80
    environment:
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe/xx/xx/xx-latest.osm.pbf
      - DOWNLOAD_POLY=https://download.geofabrik.de/europe/xx/xx/xx.poly
    volumes:
      - osm-data:/data/database/

volumes:
  osm-data:
```

i run docker compose first with "import" and then again with "run". Importing succeeds it writes stuff to the database. Server starts fine but, no matter what pbf i specify the only thing that gets rendered is Luxemburg. 

It does download the correct files. Logs from import show:

`2023-10-02 10:13:46 (14.3 MB/s) - ‘/data/region.osm.pbf’ saved [84021811/84021811]`
