### ISSUE TITLE
Getting "Permission denied" when trying to start the tile server container with docker-compose

### ISSUE THREAD

**Issue by ghevge** [Overv/openstreetmap-tile-server#393]
I'm trying to start tile server container with docker-compose, but I am getting a weird permission deniend error.

The file system volume /data/database folder has 777 permissions:

```
 [root@localhost data]# ls -ltr
total 28
drwxrwxrwx. 2 root root 16384 Oct  2 17:14 lost+found
drwxrwxrwx. 2 root root  4096 Oct  2 17:41 package
drwxrwxrwx. 2 root root  4096 Oct  2 17:42 docker
drwxrwxrwx. 3 root root  4096 Oct  2 17:58 database
```

The docker-compose.yml looks like this:

```
version: "3.8"

services:
  tile-service:
    image: overv/openstreetmap-tile-server
    container_name: tile-service
    environment:
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - THREADS=22
      - FLAT_NODES=enabled
      - UPDATES=enabled
    volumes:
      - /data/database/:/data/database/
      - /data/package/planet-230925.osm.pbf:/data/region.osm.pbf
    networks:
      mw-network:
        aliases:
          - tile-service
    ports:
      - "8080:80"
    command: "import"
    restart: always

networks:
  mw-network:
    external:
      name: mw-network
```

The last lines of the container logs are: 

```
......
657dc4f4e9ab_tile-service | symbols' ']'
657dc4f4e9ab_tile-service | + '[' '!' -f /data/style/mapnik.xml ']'
657dc4f4e9ab_tile-service | + '[' import == import ']'
657dc4f4e9ab_tile-service | + mkdir -p /data/database/postgres/
657dc4f4e9ab_tile-service | + chown renderer: /data/database/
657dc4f4e9ab_tile-service | chown: changing ownership of '/data/database/': Permission denied
```
Any idea how I can get rid of this error? 

Thanks
