### ISSUE TITLE
Is there a way to stop and then resume the import?

### ISSUE THREAD

**Issue by ghevge** [Overv/openstreetmap-tile-server#394]
I'm trying to import the whole worlds into my test tiles server, but the import operation is very time consuming. So I would like to stop it at some point and resume it later. Is that possible? If yes, how?

I was trying to just kill the import container, and then restart it, but during the restart, the container fails to start, while trying to recreate a role in the DB.

My import docker-compose looks like this:

```
version: "3.8"

services:
  tile-service:
    image: overv/openstreetmap-tile-server
    container_name: tile-service
    deploy:
      resources:
        limits:
          cpus: 20
          memory: 58G
    environment:
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - THREADS=22
      - FLAT_NODES=enabled
    volumes:
      - /data/database/:/data/database/
      - /data/package/planet-230925.osm.pbf:/data/region.osm.pbf
    networks:
      mw-network:
        aliases:
          - tile-service
    ports:
      - "8080:80"
    command: "import"

networks:
  mw-network:
    external:
      name: mw-network
```
