### ISSUE TITLE
How to log Http requests info to the docker logs with errors

### ISSUE THREAD

**Issue by Manoj-py** [Overv/openstreetmap-tile-server#427]
The docker logs stay at renderd log and remain static but as a developer we need to know who is making the request what is response give by the server if the request was not been to processed it need to be log what was bad in the request so that we when requesting for tile we can setup certain conditions 

Example: When ever there a user request for zoom level behind the limit we need to get logs in the openstreetmap-tile-server stating that the user has request for a invalid zoom level so it was not able to give a tile

**Comment by dynax60** [comment]
The virtual web server configuration in Apache2 is configured like this:

/etc/apache2/sites-enabled/000-default.conf:
```

<VirtualHost *:80>
    ServerAdmin webmaster@localhost

    AddTileConfig /tile/ default
    LoadTileConfigFile /etc/renderd.conf
    ModTileRenderdSocketName /run/renderd/renderd.sock
    ModTileRequestTimeout 0
    ModTileMissingRequestTimeout 30

    DocumentRoot /var/www/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <IfDefine ALLOW_CORS>
        Header set Access-Control-Allow-Origin “*”
    </IfDefine>
</VirtualHost>

```

```
# grep -w APACHE_LOG_DIR /etc/apache2/envvars
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX
```

So just mount the local log directory to /var/log/apache2. Example docker-compose.yml:
```yaml

services:
  import:
    image: overv/openstreetmap-tile-server
    shm_size: 256m
    volumes:
      - ./style:/data/style
      - ./osm-data:/data/database
      - osm-tiles:/data/tiles
      - ./logs:/var/log/apache2
    environment:
      THREADS: 32
    ports:
      - “80:80”
    command: run

volumes:
  osm-tiles:
    external: true

```
