### ISSUE TITLE
Cannot mount multiple import files in Kubernetes pod - change data import path to /data/import

### ISSUE THREAD

**Issue by mreiche** [Overv/openstreetmap-tile-server#438]
I have a Podspec like:
```yaml
volumes:
  - name: import-data
    persistentVolumeClaim:
      claimName: osm-import-data
  - name: database
    persistentVolumeClaim:
      claimName: osm-database
volumeMounts:
    - mountPath: /data/region.osm.pbf
      name: import-data
      readOnly: true
      subPath: region.osm.pbf
    - mountPath: /data/region.poly
      name: import-data
      readOnly: true
      subPath: region.poly
    - mountPath: /data/database
      name: database
```
where `import-data` contains the following files:
`/data/region.osm.pbf` and `/data/region.poly`

But the container has only mounted the last file `/data/region.poly`. AFAIK, this is a limitation of Kubernetes, that you cannot mount multiple files into the same directory `/data`.
```
Filesystem                                              Size  Used Avail Use% Mounted on
overlay                                                 437G   24G  394G   6% /
tmpfs                                                    64M     0   64M   0% /dev
/dev/pvc-578fda66-ff58-4395-87ff-dc85c82d7f12  9.8G  4.2G  5.6G  43% /data/region.poly
/dev/pvc-43f80f5e-0685-4484-8502-32f3f7475243  196G   32G  165G  16% /data/database
...
```

Therefore I request to change the import directory to `/data/import`, which would make this possible and mounting the data much easier like:
```yaml
volumeMounts:
    - mountPath: /data/import
      name: import-data
      readOnly: true
    - mountPath: /data/database
      name: database
```
